name: build BWCE_Final

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'       
    - name: configure bw6-maven-plugin
      run: |
        cd ~
        wget -q -t=3 https://github.com/TIBCOSoftware/bw6-plugin-maven/releases/download/v2.8.1/TIB_BW_Maven_Plugin_2.8.1.zip
        unzip TIB_BW_Maven_Plugin_2.8.1.zip -d TIB_BW_Maven_Plugin_2.8.1
        unzip ./TIB_BW_Maven_Plugin_2.8.1/config/bw6-maven-plugin.zip -d ./TIB_BW_Maven_Plugin_2.8.1/config/bw6-maven-plugin 
        cd ./TIB_BW_Maven_Plugin_2.8.1/config/bw6-maven-plugin        
        bash install.sh 
    - name: Build with Maven
      run: mvn -B package --file tibco.bwce.sample.binding.rest.BookStore.application.parent/pom.xml