name: build BWCE

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'       
    - name: Build with Maven
      run: mvn -B package --file tibco.bwce.sample.binding.rest.BookStore.application.parent/pom.xml
    - name: show contents
      if: ${{ failure() }}
      run: |
        echo "Current Directory"
        pwd
        ls -al
        echo "Home Directory"
        cd ~
        pwd
        ls -al
        echo "inside .m2"
        cd .m2
        ls -al
        echo "Content of Settings.xml"
        cat settings.xml
        echo "inside repository"
        cd repository
        ls -al
        echo "inside tibco plugins folder"
        cd com/tibco/plugins
        ls -l 
        echo "inside com.tibco.bw.palette.shared"
        cd com.tibco.bw.palette.shared
        ls -al
        echo "inside 6.1.100"
        cd 6.1.100
        ls -al
