name: build BWCE_New

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'       
    - name: show contents
      run: |
        echo "Current Directory"
        pwd
        ls -al
        echo "Home Directory"
        cd ~
        pwd
        ls -al
        mkdir ~/bw6_maven_plugin
        cd bw6_maven_plugin
        curl https://github.com/TIBCOSoftware/bw6-plugin-maven/releases/download/v2.8.1/TIB_BW_Maven_Plugin_2.8.1.zip
        unzip TIB_BW_Maven_Plugin_2.8.1.zip.zip
        ls -al