name: build BWCE_Final

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'       
    - name: show contents
      run: |
        cd ~
        wget -q -t=3 https://github.com/TIBCOSoftware/bw6-plugin-maven/releases/download/v2.8.1/TIB_BW_Maven_Plugin_2.8.1.zip
        unzip TIB_BW_Maven_Plugin_2.8.1.zip -d TIB_BW_Maven_Plugin_2.8.1
        unzip ./TIB_BW_Maven_Plugin_2.8.1/config/bw6-maven-plugin.zip -d ./TIB_BW_Maven_Plugin_2.8.1/config/bw6-maven-plugin 
        cd ./TIB_BW_Maven_Plugin_2.8.1/config/bw6-maven-plugin        
        bash install.sh    
        echo "confirming the installation"
        cd ~
        pwd
        ls -al
        echo "inside .m2"
        cd .m2
        ls -al
        echo "Content of Settings.xml"
        cat settings.xml
        echo "inside repository"
        cd repository
        ls -al
        echo "inside tibco plugins folder"
        cd com/tibco/plugins
        ls -l 
        echo "inside com.tibco.bw.palette.shared"
        cd com.tibco.bw.palette.shared
        ls -al
        echo "inside 6.1.100"
        cd 6.1.100
        ls -al

