name: build BWCE_New

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'       
    - name: show contents
      run: |
        echo "Current Directory"
        pwd
        ls -al
        echo "Home Directory"
        cd ~
        pwd
        ls -al
        mkdir ~/bw6_maven_plugin
        cd bw6_maven_plugin
        pwd
        curl -sL https://api.github.com/repos/TIBCOSoftware/bw6-plugin-maven/releases/latest | jq -r '.assets[].browser_download_url'         echo "inside the downloaded folder"
        ls -al
