name: Shell commands

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: pwd n ls
      run: |
        pwd
        ls -al
    - name: Build with Maven
      run: mvn -B package --file pom.xml