name: build BWCE

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: pwd n ls
      run: |
        pwd
        ls -al
        cd ~
        ls -al
        cd .m2
        ls -al
        cat settings.xml
        cd repository
        ls -al
        cd com/tibco/plugins
        ls -l        
    - name: Build with Maven
      run: mvn -B package --file tibco.bwce.sample.binding.rest.BookStore.application.parent/pom.xml
