name: check runner
on: [ workflow_dispatch ]

jobs:
  setup-runner:
    runs-on: [ self-hosted ] 
    name: check runner
    steps:     
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run on runner
      run: |
       cd ~
       curl -fsSL https://get.docker.com -o get-docker.sh
       sudo sh get-docker.sh
       docker version
