name: check runner
on: [ workflow_dispatch ]

jobs:
  setup-runner:
    runs-on: [ self-hosted ] 
    name: check runner
    steps:     
    - name: Run on runner
      run: |
       cd ~
       docker version