name: Deploy_BWCE

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'    
    - name: OC Login and set context
      uses: redhat-actions/oc-login@v1
      env:
        OPENSHIFT_USER: ${{ secrets.USER }}
        OPENSHIFT_NAMESPACE: ${{ secrets.MY_NAMESPACE }}

      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        openshift_username: ${{ env.OPENSHIFT_USER }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}        
    - name: Deploy App to OpenShift
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        oc import-image teststream --from=rohitbajwa/tibco.bwce.sample.binding.rest.bookstore.application_1.0.0_dev:latest --confirm
        oc new-app teststream:latest
        oc status
        