name: OpenShift Self-Hosted setup Workflow
on: [ workflow_dispatch ]

jobs:
  setup-runner:
    runs-on: [ self-hosted ] 
    name: Install runner
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'       
    - name: configure bw6-maven-plugin
      run: |
       cd ~
       mkdir maven_installation
       cd maven_installation/
       curl -sSLf -O https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
       tar xzvf apache-maven-3.8.1-bin.tar.gz
       export PATH=/home/runner/_work/_tool/Java_Adopt_jdk/11.0.11-9/x64/bin:$PATH
       export JAVA_HOME=/home/runner/_work/_tool/Java_Adopt_jdk/11.0.11-9/x64
       export PATH=/home/runner/maven_installation/apache-maven-3.8.1/bin:$PATH
       cd ~
       mkdir bw6_maven_plugin
       cd bw6_maven_plugin
       git clone https://github.com/RohKumarT/Maven_Plugin.git
       cd Maven_Plugin
       chmod 755 ./install.sh