name: Test Self Hosted Runner

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: [ self-hosted ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Maven
      run: |      
        export JAVA_HOME=/home/runner/_work/_tool/Java_Adopt_jdk/11.0.11-9/x64
        export PATH=/home/runner/_work/_tool/Java_Adopt_jdk/11.0.11-9/x64/bin:$PATH        
        export PATH=/home/runner/maven_installation/apache-maven-3.8.1/bin:$PATH
        echo $PATH
        mvn -B clean package --file tibco.bwce.sample.binding.rest.BookStore.application.parent/pom.xml

        