name: Test Self Hosted Runner

on : workflow_dispatch

jobs:
  build-ear:
    runs-on: [ self-hosted ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Maven
      env:
        JAVA_HOME: /home/runner/_work/_tool/Java_Adopt_jdk/11.0.11-9/x64
        PATH: /home/runner/maven_installation/apache-maven-3.8.1/bin:/home/runner/_work/_tool/Java_Adopt_jdk/11.0.11-9/x64/bin:$PATH
      run: |      
        mvn -B clean package --file tibco.bwce.sample.binding.rest.BookStore.application.parent/pom.xml
    - name: OC Login and set context
      uses: redhat-actions/oc-login@v1
      env:
        OPENSHIFT_USER: ${{ secrets.USER }}
        OPENSHIFT_NAMESPACE: ${{ secrets.MY_NAMESPACE }}
        PATH: /home/runner/_work/_tool/oc/4.6/x64:$PATH

      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        openshift_username: ${{ env.OPENSHIFT_USER }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Deploy App to OpenShift
      run: |
        oc import-image bookstore --from=rohitbajwa/tibco.bwce.sample.binding.rest.bookstore.application_1.0.0_dev:latest --confirm
        oc new-app bookstore:latest --name bookstore
        oc status

        